% Each new term in the Fibonacci sequence is generated by adding
% the previous two terms. By starting with 1 and 2, the first 10
% terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values
% do not exceed four million, find the sum of the even-valued terms.
% answer is 4613732

% Generate fibonacci sequence, with values not exceeding 4 million

f=1:2;
max=4000000;
for n=3:1000
    f(n)=f(n-1)+f(n-2);
    if f(n)>max
        break
    end
end

% Sum of even valued terms of sequence
tot=0;
for i=1:n
    if rem(f(i),2)==0
        tot=tot+f(i);
    end
end

tot



