/*
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
answer is 4613732
 */

package src;

public final class q002 implements Euler{

    public String solve()
    {
        int prvVal = 1;
        int curVal = 2;
        int runningSum = 2;
        int nxtVal = 3;

        while (nxtVal<=4000000){
            if (nxtVal%2==0){
                runningSum = runningSum + nxtVal;
            }
            nxtVal = prvVal + curVal;
            prvVal = curVal;
            curVal = nxtVal;
        }


        return String.valueOf(runningSum);
    }
}
